### ISSUE TITLE
Signing messages

### ISSUE THREAD

**Issue by sethf200** [lucanaef/PGPro#36] opened 2021-03-12 16:19 UTC
Just a thought. Can we add in the ability to sign messages with our keys in the app. I've looked everywhere for a signing feature but it seems to be missing. Would it be possible to add it in?

**Comment by lucanaef** [comment] 2021-03-28 09:49
Yes, it will be coming! I'm closing this issue as it is a duplicate of #25 but thank you for the input.

**Closed by lucanaef** 2021-03-28 09:49 UTC
