### ISSUE TITLE
Suggestion to add file encryption

### ISSUE THREAD

**Issue by serstkov** [lucanaef/PGPro#37] opened 2021-03-29 11:57 UTC
Hey. Super cool app. Just thought I would suggest to add file encryption option as well. Might be very useful for some people on the go. 

Justas

**Comment by lucanaef** [comment] 2021-04-27 10:44
Thanks for the suggestion! I'll consider implementing this maybe some time after Yubikey support :-)

**Comment by lucanaef** [comment] 2021-04-27 10:45
I'll close this as it is a duplicate of #21.

**Closed by lucanaef** 2021-04-27 10:45 UTC
