### ISSUE TITLE
App crashes when trying to decrypt

### ISSUE THREAD

**Issue by SerafinDinges** [lucanaef/PGPro#62] opened 2021-10-14 16:57 UTC
Might just be a user error as this seems to be too a basic functionality to not be working, but still. Here's my error and how to reproduce:

1. I have an encrypted e-mail in the Apple Mail app. I have clicked on the encrypted message attachment (`encrypted.asc`) and click on PGPro in the share screen.
2. So far so good. The encrypted content is displayed in the Decryption window, I can select my key and enter my passphrase. I click on the open envelope on the top right and:
3. The app just shuts down and when I restart all the details are gone.

Am I doing something wrong? Is there something wrong with my key? The same key works on macOS Mail using GPGTools.

Some things I've tried:
- Manually pasting encrypted contents
- Entering a wrong password (get an error message, so I'm using the right one)

Using an iPhone 12, iOS 15.0.1

Let me know if I can provide you with anything or try anything. Thank you for this!

**Comment by lucanaef** [comment] 2021-10-16 15:24
Thanks for opening the issue! This does not sound like user error to me.

Just to clarify: Does it work when manually pasting the encrypted message?

If not, could you try and reproduce this issue on the newest beta (https://testflight.apple.com/join/BNawuaNF)? 
It sounds like the cryptography framework crashes in the background. The new beta uses an updated version of that framework which might already solve the problem.

**Comment by SerafinDinges** [comment] 2021-10-18 09:00
Hi Luca! Amazing, that solved it. Now it works as expected. Thanks for getting back to me so quickly!

Just to confirm: Yes it crashed no matter how I entered the encrypted message.

Let me know if you need any info from to investigate further. Just for documentation, here some details on the key:

- Length: 3072
- Algorithm: RSA
- Capabilities: ESC

(I did just realise Umlauts aren't being decoded, but that's not a big deal. Maybe a note for the future.)

**Comment by lucanaef** [comment] 2021-11-14 12:44
Since I just released version 2021.4 that was in beta at the time and fixed it, I'll close this issue. If any problems occur, feel free to (re-)open an issue!

(I keep the mentioned decoding issues in mind)

**Closed by lucanaef** 2021-11-14 12:44 UTC
Labels: bug
