### ISSUE TITLE
Message is invalid! 

### ISSUE THREAD

**Issue by ygrange** [lucanaef/PGPro#19] opened 2020-07-24 11:43 UTC
When I try to decrypt a message that was sent to me by sending the msg.asc file to PGPro on my iPhone, I can not decrypt it because of the "Message is invalid!" error. I have my private key imported. It seems to make no difference whether or not I specify my password. I am not sure what goes wrong here. Apart from the msg.asc, the messae also shows a Part.000 file attached. Not sure if that somehow causes the issue here.

**Comment by lucanaef** [comment] 2020-07-29 12:31
If possible, please send .asc-file that triggers this issue to dev@pgpro.app so that I can reproduce it.

**Comment by ygrange** [comment] 2020-07-31 11:33
Forwarded!

--
Y. Grange

> Op 29 jul. 2020 om 14:31 heeft Luca Näf <notifications@github.com> het
volgende geschreven:
> 
> ﻿
> If possible, please send .asc-file that triggers this issue to
dev@pgpro.app so that I can reproduce it.

**Comment by lucanaef** [comment] 2020-08-26 16:13
Thanks! I've finally had some time to look at this. The issue was caused by extra newline characters that got inserted at some point. The problem should be fixed in the next version.

**Closed** 2020-08-26 16:14 UTC
